services:
  receive:
    build: "receive/"
    restart: unless-stopped
    volumes:
      - thread-art-vol:/thread-art-vol
  act:
    build: "act/"
    restart: unless-stopped
    volumes:
      - thread-art-vol:/thread-art-vol
  server:
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "1025:80"
      #- "80:80"
      #- "443:443"
      #- "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - ./frontend:/srv:Z
      - caddy_data:/data
      - caddy_config:/config
volumes:
  thread-art-vol:
