apiVersion: v1
kind: Pod
metadata:
  name: thread-art-server
spec:
  containers:
    - name: thread-art-receive
      image: receive
      ports:
        - containerPort: 8001
      volumeMounts:
        - mountPath: /app/thread-art-vol
          name: thread-art-vol
    - name: thread-art-act
      image: act
      volumeMounts:
        - mountPath: /app/thread-art-vol
          name: thread-art-vol
  volumes:
    - name: thread-art-vol
      persistentVolumeClaim:
        claimName: thread-art-volume
